config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'default/index'
  get 'default/about'

  resources :questions
  # get 'questions/index'
  # get 'questions/create'
  # get 'questions/new'
  # get 'questions/destroy'
  # get 'questions/show'

  get 'trivia/index'
  get 'trivia/answer'
  get 'trivia/submit'

  root 'default#index'
  match '/:action(/:id)', controller: 'default', via: %i[get post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  field :answer_index, type: Integer
  field :is_correct, type: Boolean
  field :points_awarded, type: Integer

  has_one :answer_user, class_name: 'User'
  has_one :question_id, class_name: 'Question'
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :answers, class_name: 'QuestionAnswer'
  has_many :answer_submitions, class_name: 'Answer'
  belongs_to :question_user, class_name: 'User'

  field :tags, type: Array, default: []
  field :correct_answer_index, type: Integer, default: -1
  field :question_text, type: String
  field :question_reveal_text, type: String
end

app/models/question_answer.rb
class QuestionAnswer
  include Mongoid::Document
  field :answer_text, type: String

  embedded_in :question, class_name: 'Question'
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :questions
  has_many :answers

  field :first_name, type: String
  field :last_name, type: String
  field :agree_terms, type: Boolean, default: false

  field :points, type: Integer

  #
  #  GENRATED BY DEVISE
  #
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name email password agree_terms])
  end
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  include DefaultHelper
  before_action :set_trivia, only: [:index], if: -> { user_signed_in? }
  skip_before_action :authenticate_user!

  def index
    return if user_signed_in?
    redirect_to new_user_session_url
  end

  def about
  end

  private

  def set_trivia
    @trivia_questions = trivia_questions_preview
    @trivia_questions_count = trivia_questions_count
    @my_questions = my_questions_recent
    @my_questions_count = my_questions_count
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def new
    @question = Question.new(
      answers: [QuestionAnswer.new(answer_text: ''), QuestionAnswer.new(answer_text: '')],
      correct_answer_index: 0
    )
  end

  def create
    @question = Question.new(new_question_params)
    @question.question_user = current_user

    params[:question][:answers].each do |v|
      @question.answers.push QuestionAnswer.new(answer_text: v)
    end

    @question.save!

    flash[:alert] = 'Save Successful!'
    redirect_to new_question_url
  end

  def edit
    @question = Question.find(params[:id])
  end

  def show
  end

  def update
    @question = Question.find(params[:id])

    # // this is hacky, find a better way to map or handle checkboxes
    answers = []
    params[:question][:answers].each do |v|
      answers.push QuestionAnswer.new(answer_text: v)
    end
    @question.answers = answers

    @question.update(edit_question_params)

    flash[:alert] = 'Update Successful!'
    redirect_to questions_path
  end

  private

  def new_question_params
    params.require(:question).permit(:question_text, :question_reveal_text, :answers, :correct_answer_index)
  end

  def edit_question_params
    params.require(:question).permit(:question_text, :question_reveal_text, :correct_answer_index)
  end
end

app/controllers/trivia_controller.rb
class TriviaController < ApplicationController
  include TriviaHelper
  before_action :index
  def index
    @trivia_questions = get_trivia_questions_current_user(current_user.id)
  end

  def answer
    @trivia_question = get_trivia_question(params[:id])
  end

  def submit
    @trivia_question = get_trivia_question(params[:id])

    @answer = Answer.new(new_answer_params)
    @answer.user = current_user
    @answer.save!

    flash[:alert] = 'Save Successful!'
    redirect_to new_question_url
  end

  private

  def new_question_params
    params.require(:answer).permit(:answer_index, :is_correct, :points_awarded, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/default_helper.rb
module DefaultHelper
  def my_questions_recent
    # order by create?
    Question.where(question_user: current_user).limit(3).only(:id, :question_text, :owner_id)
  end

  def my_questions_count
    Question.where(question_user: current_user).count
  end

  def trivia_questions_preview
    Question.not_in(question_user: current_user).limit(3).only(:id, :question_text)
  end

  def trivia_questions_count
    Question.not_in(question_user: current_user).count
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/trivia_helper.rb
module TriviaHelper
  def get_tags(user)
  end

  def get_trivia_questions_current_user(id)
    Question.not_in(question_user: current_user).only(:id, :question_text)
  end

  def get_trivia_question(id)
    Question.only(:id, :question_text, :question_reveal_text, :answers).find(id)
  end
end

app/views/default/about.html.erb
<h1>Default#about</h1>
<p>Find me in app/views/default/about.html.erb</p>

app/views/default/index.html.erb
<h2>Welcome, <%= current_user.first_name %>!</h2>
<p>You have, <%= @trivia_questions_count %>, unanswered trivia questions to answer.</p>

<div class="row">
    <div class="col-sm-4">
        <h3>I've got Answers!</h3>
        <ul class="list-group">
            <li class="list-group-item">
                <%= link_to "Answer Trivia Questions", trivia_index_path %>
            </li>
        </ul>
        <% if @trivia_questions_count > 0  %>
            <ul class="list-group">
            <% @trivia_questions.each do |t| %>
                <li class="list-group-item">
                    <h4><%= t.question_text.truncate(60, separator: ' ') %></h4>
                    <%= link_to(controller: "trivia", action: "answer", id: t.id ) do %>
                        <span class="glyphicon glyphicon-edit"></span> Answer This
                    <% end %>
                </li>
            <% end %>
            <% if @trivia_questions_count > 3 %>
                <li class="list-group-item">
                    <%= link_to "...More!", trivia_index_path %>
                </li>
            <% end %>
            </ul>
            
        <% end %>
    </div>
    <div class="col-sm-4">
        <h3>I have Questions!?</h3>
        <ul class="list-group">
            <li class="list-group-item">
                <%= link_to "Ask Question", new_question_path %>
            </li>
        </ul>
        <% if @my_questions_count > 0  %>
            <ul class="list-group">
            <% @my_questions.each do |q| %>
                <li class="list-group-item">
                    <h4><%= q.question_text %></h4>
                    <%= link_to(controller: "questions", action: "edit", id: q.id ) do %>
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    <% end %>
                </li>
            <% end %>
            </ul>
        <% end %>

    </div>
    <div class="col-sm-4">
        <h3>View Top Scores</h3>
    </div>
  </div>    
  
</div>

app/views/layouts/_header.html.erb
  <nav class='navbar navbar-inverse'>

    <div id="branding">
        <h1 class="logo">
            <%= link_to("Trivia Planet", root_path) %>
        </h1>
        <span class="tagline">Your place for endless Trivia</span>
    </div>

    <div class='navbar-header'>
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
            <span class='sr-only'>Toggle navigation</span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
        </button>
    </div>
    <!-- <div class='clearfix'></div> -->
    <div class='navbar-collapse collapse'>
        <ul class='nav navbar-nav navbar-right'>
            <li>
                <%= link_to(root_path) do %>
                    <span class="glyphicon glyphicon-home"></span> Home
                <% end %>
            </li>
            <li>
                <%= link_to(root_path) do %>
                    <span class="glyphicon glyphicon-question-sign"></span> About
                    <% end %>
            </li>

            <% if user_signed_in? %>
                <li>
                    <%= link_to(destroy_user_session_path, method: :delete) do %>
                        <span class="glyphicon glyphicon-log-out"></span> Log Out
                    <% end %>
                </li>
            <% end %>

        </ul>
        
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trivia Planet</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render partial: "layouts/header" %>
    </header>

    <div class="container">
      <div class="row">
          <div class="col-sm-12">
            <%= yield %>
          </div>
      </div>    
    </div>

    <% if !alert.nil? | !notice.nil? %>
    <div id="message">              
      <% if !alert.nil? %>            
        <div class="alert alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>
      <% if !notice.nil? %>
        <div class="alert alert-warning" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
    </div>
    <% end %>

  </body>
</html>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>

<%= form_with scope: :question, method: :put, url: question_path(@question),  local: true do |f| %>
  <h3>Ask your question below</h3> 
  <div class="field form-group">
    <%= f.label :question_text %><br />
    <%= f.text_area :question_text, cols: 80, rows: 5, class: 'form-control', autofocus: true %>
  </div>

  <h3>Answers</h3>

  <div class="answer_options">  
      <ul id="answer_list" class="list-group">
        <% @question.answers.each do |a| %>
        <li class="list-group-item">
            <input type="text" name="question[answers][]" value="<%= a.answer_text %>" class="form-control" />
            <div class="button-group">
              <a href="#" class="btn set_answer">
                <span class="glyphicon glyphicon-edit"></span> Set as Correct
              </a>
              <a href="#" class="btn remove_answer">
                <span class="glyphicon glyphicon-delete"></span> Remove
              </a>
            </div>
        </li>
        <% end %>
      </ul>

      <a href="#" class="btn btn-default add_answer">Add An Answer Option</a>
  </div>
  <p></p>

  <div class="field form-group">
    <%= f.label :question_reveal_text, "Reveal Text: Give more information about this question AFTER it is answered." %><br />
    <%= f.text_area :question_reveal_text, cols: 80, rows: 10, class: 'form-control' %>
  </div>

  <%= f.hidden_field :correct_answer_index, id: 'correct_answer_index' %>
  <div class="actions">
    <%= f.submit "Update", class: "btn btn-warning" %>
    <%= link_to "Cancel", default_index_path, class: "btn btn-info" %>
  </div>

<% end %>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h2>Add New Question</h2>

<%= form_with scope: :question, url: questions_path,  local: true do |f| %>
  <h3>Ask your question below</h3> 
  <div class="field form-group">
    <%= f.label :question_text %><br />
    <%= f.text_area :question_text, cols: 80, rows: 5, class: 'form-control', autofocus: true %>
  </div>

  <h3>Answers</h3>

  <div class="answer_options">  
      <ul id="answer_list" class="list-group">
        <% @question.answers.each do |a| %>
        <li class="list-group-item">
            <input type="text" name="question[answers][]" value="<%= a.answer_text %>" class="form-control" />
            <div class="button-group">
              <a href="#" class="btn set_answer">
                <span class="glyphicon glyphicon-edit"></span> Set as Correct
              </a>
              <a href="#" class="btn remove_answer">
                <span class="glyphicon glyphicon-delete"></span> Remove
              </a>
            </div>
        </li>
        <% end %>
      </ul>

      <a href="#" class="btn add_answer">Add An Answer Option</a>
  </div>
  <p></p>

  <div class="field form-group">
    <%= f.label :question_reveal_text, "Reveal Text: Give more information about this question AFTER it is answered." %><br />
    <%= f.text_area :question_reveal_text, cols: 80, rows: 10, class: 'form-control' %>
  </div>

  <%= f.hidden_field :correct_answer_index, id: 'correct_answer_index' %>
  <div class="actions">
    <%= f.submit "Save and Continue", class: "btn btn-warning" %>
    <%= link_to "Finish", default_index_path, class: "btn btn-info" %>
  </div>

<% end %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/trivia/answer.html.erb
<h2 class="question"><%= @trivia_question.question_text %></h2>

<%= form_with scope: :question, url: questions_path,  local: true do |f| %>
  <p>Choose your answer</p>
  <ul class="list-group">
    <% @trivia_question.answers.each_with_index do |a, index| %>
        <li class="list-group-item">
            
            <%= radio_button_tag 'question_answer', index, false, class:'float-left', id: 'answer' + index.to_s %>
            <label for="<%= 'answer' + index.to_s %>" class=""><%= a.answer_text %></label>
        </li>
    <% end %>
  </ul>
  <p>DISPLAY TAGS</p>
  <p>RANK</p>

  <div class="actions">
    <%= f.submit "Submit & Continue", class: "btn btn-warning" %>
    <%= link_to "Done", trivia_index_path, class: "btn btn-info" %>
  </div>

<% end %>

app/views/trivia/index.html.erb
<h2>Trivia List</h2>

FILTER BY TAGS, ANSWERED_BOOLEAN, LAZY_LOADING

<% if !@trivia_questions.nil? %>
    <ul class="list-group">
    <% @trivia_questions.each do |t| %>
        <li class="list-group-item">
            <%= t.question_text.truncate(260, separator: ' ') %><br />
            <%= link_to(controller: "trivia", action: "answer", id: t.id ) do %>
                <span class="glyphicon glyphicon-edit"></span> Answer This
            <% end %>
        </li>
    <% end %>
    </ul>
<% end %>